{% set name = "code-server" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: c25d6167ddec41b28a7abeb73a0d0fe1d7af150e87cf185c01abb9736e222ee9  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 1a3054d3ed2a0ea453f11ea310f3c9f09c442beb1cc804ed4d5f3b0f4595b96a  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: ba055a1bdeff75d2f70ea93924a5cf6fe2c5a5c54e15fd137a68e6949f8e481f  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win or aarch64]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 16.*
  run:
    - nodejs 16.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
