{% set name = "code-server" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 3b29ad8e75b48980933cecea96218c07d3a8c79492bb31d9665b04f9a1e8aea4  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 81ee7115e850a3b81ff48e04d5a31eea29c6860041da2a098f31829180bb6acd  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: c24af1fa61707ba5a3954ef76df3055dc0b878543691aa62960482d03b357ce1  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 16.*
  run:
    - nodejs 16.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
