{% set name = "code-server" %}
{% set version = "4.91.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 0851ec5cbeef62ee340bd2725cd8863bd84ee1bacc54611cefc812ccbdd0e6e4  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 799b47dbcc3e75c3b743279dd751173a3676da47fbc56f42e49ae938a169067b  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-arm64.tar.gz  # [osx-arm64]
  sha256: 779b9ccff907df5746d1160ecc2b3443d6f33b47f292d34483b7402b264a2f28  # [osx-arm64]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx-arm64]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - nodejs 18.*
  run:
    - nodejs 18.*

test:
  commands:
    - code-server --help
    - $CONDA_PREFIX/share/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin/rg --version  # [osx-arm64]

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
