{% set name = "code-server" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: eec34a53d757e8041357ba8d3ffd84080064b14585b5ba53c7829213b9136b5a  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 2028afb9a28286dea13e18ec9e8b65065a9d614a74b80dd8424a688f299059dc  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 62ebbd0e752258f00f60a88cece5c999e15abb116d18d9808334e76dd4bd5ce9  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win or aarch64]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 16.*
  run:
    - nodejs 16.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
