{% set name = "code-server" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: d34b0b79582196d59d44ac971aabb7f15cb05d837318b94f62470dc8475665e9  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 1567f7217f21f2ab025c31e81932f5103b5a902c529f99c5a6c8c6f9ad40086a  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 653b078db0edea3eb9d8b1a2da70d676f67e096d2015ac7b0e08a69bcac74221  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 14.*
  run:
    - nodejs 14.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE.txt
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
