{% set name = "code-server" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: d3ca41a55e36d73d80300702af2687e25d440cff6b613bb58a2c88d9b8a0a38f  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 7aefba0bf5eef64b307e798b501431c73b88ba485b42e226e8294858c91434f7  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: e0bfb873ea1c7548ef3c832b0315dc44d1fa730e5d42be12a642441dd066e9ec  # [osx]
  folder: code-server

build:
  number: 1
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 14.*
  run:
    - nodejs 14.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE.txt
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
