{% set name = "code-server" %}
{% set version = "4.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: da19233080f97b3320514000ad8bf0bb3bd4b1ebf19bcb487c31c04dde7efdef  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: d809153ddd53f4e531020e9bef8729e6ae71ea873d41f916e8ecebbf614201da  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 27190e15a40abd0c9d78f57fe9f076128923e63d72410d87596f22b2f328fd1f  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win or aarch64]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs 16.*
  run:
    - nodejs 16.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
