{% set name = "code-server" %}
{% set version = "4.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 64835902b24d87c6e2d0d2d5a768e4a21b09314f32f5e5b42a543d4dc98415a1  # [linux64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: d896d7e810415fc473eba8dd41b3e5dfed98925532e12a0fba57949aead89c9e  # [aarch64]
  url: https://github.com/cdr/code-server/releases/download/v{{ version }}/code-server-{{ version }}-macos-amd64.tar.gz  # [osx]
  sha256: 2f8be01c3e18ea8f701df7f0ebd299e3c5c189cbbc2c8fcbc8706e4f5cab6fe2  # [osx]
  folder: code-server

build:
  number: 0
  binary_relocation: false  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - nodejs 18.*
  run:
    - nodejs 18.*

test:
  commands:
    - code-server --help

about:
  home: https://github.com/cdr/code-server
  license: MIT
  license_family: MIT
  license_file:
    - code-server/LICENSE
    - code-server/ThirdPartyNotices.txt
  summary: Run VS Code on a remote server.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
